repos:
  # Python関連
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        language_version: python3.12
        files: ^backend/.*\.py$

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.11.13
    hooks:
      - id: ruff
        files: ^backend/.*\.py$
        args: [--fix, --exit-non-zero-on-fix]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.16.0
    hooks:
      - id: mypy
        files: ^backend/.*\.py$
        additional_dependencies: [types-requests, types-PyYAML]

  # JavaScript/TypeScript関連
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        files: ^frontend/.*\.(js|jsx|ts|tsx|json|css|md|yml|yaml)$
        exclude: ^frontend/(node_modules/|dist/|build/|coverage/)

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.28.0
    hooks:
      - id: eslint
        files: ^frontend/.*\.(js|jsx|ts|tsx)$
        additional_dependencies:
          - '@typescript-eslint/eslint-plugin@^6.0.0'
          - '@typescript-eslint/parser@^6.0.0'
          - 'eslint-config-prettier@^9.0.0'

  # インフラストラクチャ関連
  - repo: local
    hooks:
      - id: terraform-fmt
        name: Terraform Format
        entry: terraform fmt -recursive
        language: system
        files: ^infra/terraform/.*\.tf$
        pass_filenames: false

      - id: bicep-build
        name: Bicep Build Check
        entry: sh -c 'cd infra/bicep && az bicep build --file main.bicep --stdout > /dev/null'
        language: system
        files: ^infra/bicep/.*\.bicep$
        pass_filenames: false

  # セキュリティ関連
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
        exclude: |
          (?x)^(
            .*\.lock$|
            .*node_modules/.*|
            .*\.terraform/.*|
            .*coverage/.*
          )$

  # 一般的なチェック
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        exclude: ^frontend/(node_modules/|dist/|build/)
      - id: end-of-file-fixer
        exclude: ^frontend/(node_modules/|dist/|build/)
      - id: check-yaml
        exclude: ^frontend/(node_modules/|dist/|build/)
      - id: check-json
        exclude: ^frontend/(node_modules/|dist/|build/)
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: check-case-conflict
      - id: check-merge-conflict

  # Dockerファイル
  - repo: https://github.com/hadolint/hadolint
    rev: v2.13.1-beta
    hooks:
      - id: hadolint-docker
        files: Dockerfile.*

default_language_version:
  python: python3.12
  node: '20.19.1'

ci:
  autofix_prs: true
  autoupdate_schedule: monthly
