version: '3.8'

services:
  # テスト用APIサービス
  api-test:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: development
    env_file:
      - .env.test  # テスト環境設定ファイルを使用
    environment:
      # Docker専用設定（コンテナ内での動作に必要な設定のみ）
      - PYTHONPATH=/app
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    volumes:
      - ./backend:/app
      - test_cache:/root/.cache
    working_dir: /app
    command: >
      sh -c "
        echo 'Waiting for dependencies...' &&
        sleep 2 &&
        echo 'Running tests...' &&
        python -m pytest tests/ -v --cov=. --cov-report=term-missing --cov-report=html --tb=short
      "
    networks:
      - test-network

volumes:
  test_cache:

networks:
  test-network:
    driver: bridge
