version: '3.8'

services:
  # テスト用APIサービス
  api-test:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: development
    environment:
      - ENV=test
      - LOG_LEVEL=DEBUG
      - PYTHONPATH=/app
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - QRAI_DATABASE_URL=sqlite+aiosqlite:///./test.db
      - LLM_PRIMARY_PROVIDER=mock
      - LLM_FALLBACK_PROVIDERS=mock
    volumes:
      - ./backend:/app
      - ./tests:/app/tests
      - test_cache:/root/.cache
    working_dir: /app
    command: >
      sh -c "
        echo 'Waiting for dependencies...' &&
        sleep 2 &&
        echo 'Running database migrations...' &&
        alembic upgrade head &&
        echo 'Running tests...' &&
        python -m pytest tests/ -v --cov=. --cov-report=term-missing --cov-report=html --tb=short
      "
    networks:
      - test-network

volumes:
  test_cache:

networks:
  test-network:
    driver: bridge
